"""add foreign key to Review

Revision ID: 346cc6e827bc
Revises: 3fd02f851bfa
Create Date: 2024-07-03 11:48:39.743234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346cc6e827bc'
down_revision = '3fd02f851bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
